name: CD - {{SERVICE_NAME}} Staging Deploy

on:
  workflow_run:
    workflows: ["CI - {{SERVICE_NAME}} Build and Push"]
    types: [completed]
    branches: [develop]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'
        type: string

env:
  AWS_REGION: ap-northeast-2
  TERRAFORM_VERSION: 1.6.0

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    # OIDC 인증을 위한 권한 설정
    permissions:
      id-token: write
      contents: read
    
    environment:
      name: staging
      url: https://api-staging.unbox.com/{{SERVICE_NAME}}/actuator/health
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # CI에서 생성된 빌드 정보 다운로드 (workflow_run인 경우)
    - name: Download build info
      if: github.event_name == 'workflow_run'
      uses: actions/download-artifact@v4
      with:
        name: build-info
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
        
    - name: Load build info
      if: github.event_name == 'workflow_run'
      run: |
        if [ -f build-info.env ]; then
          cat build-info.env >> $GITHUB_ENV
          echo "Using image tag from CI: $IMAGE_TAG"
        else
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "Using fallback image tag: ${{ github.sha }}"
        fi
        
    - name: Set manual image tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
        echo "Using manual image tag: ${{ github.event.inputs.image_tag }}"
    
    # OIDC를 사용한 AWS 인증
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-{{SERVICE_NAME}}-role
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        
    - name: Terraform Init
      working-directory: terraform/staging
      run: |
        terraform init \
          -backend-config="bucket=terraform-state-bucket" \
          -backend-config="key=services/{{SERVICE_NAME}}/staging/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}"
          
    - name: Terraform Plan
      working-directory: terraform/staging
      run: |
        terraform plan \
          -var="image_tag=${{ env.IMAGE_TAG }}" \
          -var="service_name={{SERVICE_NAME}}" \
          -out=tfplan
          
    - name: Terraform Apply
      working-directory: terraform/staging
      run: terraform apply -auto-approve tfplan
      
    # 배포 후 헬스 체크
    - name: Health Check
      run: |
        echo "⏳ Waiting for service to be ready..."
        sleep 30
        
        HEALTH_URL="https://api-staging.unbox.com/{{SERVICE_NAME}}/actuator/health"
        MAX_ATTEMPTS=10
        ATTEMPT=1
        
        while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
          echo "🔍 Health check attempt $ATTEMPT/$MAX_ATTEMPTS"
          
          if curl -f -s "$HEALTH_URL" > /dev/null; then
            echo "✅ Health check passed!"
            echo "🌐 Service URL: $HEALTH_URL"
            break
          else
            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
              echo "❌ Health check failed after $MAX_ATTEMPTS attempts"
              echo "🔍 Please check the service logs and ECS task status"
              exit 1
            fi
            echo "⏳ Health check failed, retrying in 15 seconds..."
            sleep 15
          fi
          
          ATTEMPT=$((ATTEMPT + 1))
        done
        
    # 배포 결과 출력
    - name: Deployment Summary
      if: success()
      run: |
        echo "🚀 Staging deployment completed successfully!"
        echo ""
        echo "📋 Deployment Details:"
        echo "   Service: {{SERVICE_NAME}}"
        echo "   Environment: staging"
        echo "   Image Tag: ${{ env.IMAGE_TAG }}"
        echo "   Health Check: https://api-staging.unbox.com/{{SERVICE_NAME}}/actuator/health"
        echo ""
        echo "🔍 Monitoring:"
        echo "   ECS Console: https://console.aws.amazon.com/ecs/home?region=${{ env.AWS_REGION }}#/clusters/unbox-staging-cluster/services"
        echo "   CloudWatch Logs: https://console.aws.amazon.com/cloudwatch/home?region=${{ env.AWS_REGION }}#logsV2:log-groups/log-group/%2Fecs%2F{{SERVICE_NAME}}-staging"
        
    # 배포 실패 시 롤백 안내
    - name: Rollback Instructions
      if: failure()
      run: |
        echo "❌ Staging deployment failed!"
        echo ""
        echo "🔄 To rollback to previous version:"
        echo "   1. Go to Actions tab"
        echo "   2. Run 'CD - {{SERVICE_NAME}} Staging Deploy' workflow manually"
        echo "   3. Enter the previous working image tag"
        echo ""
        echo "🔍 Troubleshooting:"
        echo "   - Check ECS service events"
        echo "   - Check CloudWatch logs"
        echo "   - Verify Terraform state"