version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "trade"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - <SUBNET_1>
              - <SUBNET_2>
            SecurityGroups:
              - <SECURITY_GROUP>
            AssignPublicIp: "DISABLED"

Hooks:
  - AfterAllowTestTraffic: "<LAMBDA_FUNCTION_ARN>"
